Sprint 17
DmnUAll/Tracker-ios pull request #4
Opened 2023-05-08 15:40 UTC by DmnUAll

Sprint_17 have been done

2023-05-31 11:05 UTC, ABashkirova requested changes

2023-05-31 11:05 UTC, ABashkirova commented on Tracker-ios/HabitCreationScreen/ViewModel/HabitCreationScreenViewModel.swift
> +            if selectedCategory != "" {
!selectedCategory.isEmpty

2023-05-31 11:05 UTC, ABashkirova commented on Tracker-ios/Services/AnalyticsService.swift
> +            print("REPORT ERROR: %@", error.localizedDescription)
печатается только ошибка, а хотелось бы еще видеть лог-дублер по ТЗ 

например так *** Track EVENT: ###, params: ### ***

2023-06-01 07:44 UTC, DmnUAll commented on Tracker-ios/CategoryCreationScreen/View/CategoryCreationScreenController.swift
> +                                         "item": K.AnalyticItemNames.none])
Fixed

2023-06-01 07:54 UTC, DmnUAll commented on Tracker-ios/Supporting Files/Helpers/Date+Extensions.swift
> +        let date2 = Date.parse("01.01.2007")
@ABashkirova Привет!
Этот код выдает случайную дату, в промежутке, между этими двумя датами (выбраны старые даты, для уменьшения вероятности пересечения с актуальными).
Этот своеобразный "костыль" - единственное, что я смог придумать для реализации увеличения\уменьшения счетчика, при  редактировании привычки. Ведь счетчик работает по количеству уникальных дат, в которые эта привычка была отмечена, как выполненная. Если брать диапазон всех возможных дат, то, с некоторой вероятностью, можно выполнить привычку в нежелательный, для пользователя, день. ( в недалеком прошлом или будущем)

2023-06-01 08:03 UTC, DmnUAll commented on Tracker-ios/Supporting Files/de.lproj/Localizable.strings
> +"MONITOR_WHAT_YOU_NEED" = "Verfolgen Sie nur, was Sie wollen";
Updated anyway :)

2023-06-01 08:04 UTC, DmnUAll commented on Tracker-ios/Services/AnalyticsService.swift
> +            print("REPORT ERROR: %@", error.localizedDescription)
Reports added

2023-06-01 08:07 UTC, DmnUAll commented on Tracker-ios/HabitCreationScreen/ViewModel/HabitCreationScreenViewModel.swift
> +            if selectedCategory != "" {
Updated

2023-06-01 08:15 UTC, ABashkirova commented on Tracker-ios/Supporting Files/Helpers/Date+Extensions.swift
> +        let date2 = Date.parse("01.01.2007")
Все еще не понимаю задачу/проблему.

Как будто бы тебе нужно выгрузить все записи выполненные и посчитать их количество. Можно отсечь от данных время, чтобы зафиксировать уникальность в рамках дня (использовать множество, еще например)

В будущее действительно не стоит ходить за записями, а еще и стоит ограничивать пользователя там их отмечать) поэтому выгрузка должна быть с предикатом по дате "< Date()"

Попробуй еще раз описать свою сложность, может пойму наконец-то))

2023-06-01 08:39 UTC, DmnUAll commented on Tracker-ios/TrackersScreen/View/TrackersScreenController.swift
> +    }
Code have been updated

2023-06-01 10:43 UTC, DmnUAll commented on Tracker-ios/Supporting Files/Helpers/Date+Extensions.swift
> +        let date2 = Date.parse("01.01.2007")
@ABashkirova 
Я просто не понимаю - как можно увеличить количество выполненных трекеров и как тогда определять их уникальность :)
По ТЗ требуется, чтобы при нажатии на +, у конкретного трекера, на главном экране - он помечался галочкой, как выполненный. Если исключить уникальность дат, то галочка просто не будет появляться, на конкретный день. 
Или я не в ту сторону думаю, возможно.

2023-06-01 11:32 UTC, ABashkirova commented on Tracker-ios/Supporting Files/Helpers/Date+Extensions.swift
> +        let date2 = Date.parse("01.01.2007")
Кажется до меня доходит) Вообще хороший вопрос, кажется проблема в продуктовой задаче. 

Я отнесу это в фидбек команде. А пока оставляй как есть :) только добавь комментарий что это костыль)

2023-06-02 14:33 UTC, MaxCode2023 commented on Tracker-ios/StatisticsScreen/View/StatisticsScreenController.swift
> +    private let noDataImage = UICreator.shared.makeImageView(withImage: K.ImageNames.noDataToAnalyze)
Интересный метод создавать элементы вёрстки через специальный класс) Удобно, если всё приложение верстать в коде

2023-06-02 14:36 UTC, MaxCode2023 commented on Tracker-ios/StatisticsScreen/View/StatisticsScreenController.swift
> +        text: "NOTHING_TO_ANALYZE".localized,
Хорошая идея с обёрткой над NSLocalizedString

2023-06-02 14:42 UTC, MaxCode2023 commented on Tracker-ios/StatisticsScreen/View/StatisticsScreenController.swift
> +        analyticsService.report(event: K.AnalyticEventNames.open,
Мне кажется, проще было сделать enum с типами ивентов и определить его в AnalyticsService, а не задавать эти типы в константах. Но это мало относится к экрану статистики, так что можно опустить этот момент)

2023-06-02 14:47 UTC, MaxCode2023 commented on Tracker-ios/StatisticsScreen/View/StatisticsScreenController.swift
> +                                params: ["screen": K.AnalyticScreenNames.statistics])
Кстати, имя вью контроллера можно получать так: NSStringFromClass(type(of: **UIViewController_Name**)).components(separatedBy: ".").last

2023-06-02 14:55 UTC, MaxCode2023 commented on Tracker-ios/StatisticsScreen/View/StatisticsScreenController.swift
> +        noDataImage.toAutolayout()
Не очень понял как метод toAutolayout() оптимизирует и улучшает код) В принципе что с ним, что без него - кол-во строк одинаково.
p.s.: постоянно вызывать translatesAutoresizingMaskIntoConstraints = false тоже дико бесит, так что понимаю твоё стремление избавиться от этого)

2023-06-02 15:07 UTC, MaxCode2023 commented on Tracker-ios/StatisticsScreen/View/StatisticsScreenController.swift
> +            stackView.gradientBorder(colors: [.ypGradientRed, .ypGradientSky, .ypGradientBlue], isVertical: false)
Это не по теме экрана статистики, но всё же - для чего ты в методе gradientBorder() используешь gradient.zPosition = 0.0 ? Что с ним, что без него - одинаково

2023-06-02 16:42 UTC, DmnUAll commented on Tracker-ios/StatisticsScreen/View/StatisticsScreenController.swift
> +                                params: ["screen": K.AnalyticScreenNames.statistics])
Согласен! Но, иногда, по запросу аналитиков - возможно понадобиться придерживаться конкретного нейминга. Если не ошибаюсь, то главный экран, в спринте, просили обозначить как Main, в отчетах аналитики. А у меня он называется совсем не так :)

2023-06-02 16:49 UTC, DmnUAll commented on Tracker-ios/StatisticsScreen/View/StatisticsScreenController.swift
> +            stackView.gradientBorder(colors: [.ypGradientRed, .ypGradientSky, .ypGradientBlue], isVertical: false)
Хм... и вправду! Убрал :)

2023-06-02 16:50 UTC, DmnUAll commented on Tracker-ios/StatisticsScreen/ViewModel/StatisticsScreenViewModel.swift
> +    private let trackersCategoryStore = TrackerCategoryStore()
Видимо - осталось от моих попыток подсчитать остальные пункты статистики. Убрал :)

2023-06-02 16:55 UTC, DmnUAll commented
@ABashkirova Привет! Сейчас отправлю ссылку запрос на ревью. Все правки выполнены, на основе твоих комментариев и некоторых комментариев MaxCode2023 (прикладываю[ ссылку](https://github.com/MaxCode2023/Tracker/pull/5) на наше кросс-ревью, в его пул реквесте).

2023-06-02 16:57 UTC, DmnUAll commented
@ABashkirova Привет! Сейчас отправлю запрос на ревью. Все правки выполнены, на основе твоих комментариев и некоторых комментариев MaxCode2023 (прикладываю [ссылку](https://github.com/MaxCode2023/Tracker/pull/5) на наше кросс-ревью, в его пул реквесте).

2023-06-03 05:05 UTC, MaxCode2023 commented on Tracker-iosTests/TrackerTests.swift
> +    }
Круто, что ты сделал тесты для экрана статистики!
Но есть нюанс - они проверяют только состояние, когда выполненных трекеров нет) А такой тест, как мне кажется, не особо полезен.
Я бы предложил в коде добавить трекер, накинуть ему счётчик (добавить выполнение) и уже после этого сделать ещё один скриншот тест. Тогда у тебя будет покрыто тестами сразу 2 состояния - без выполненных трекеров (когда отображается заглушка) и непосредственно сама статистика

2023-06-03 10:32 UTC, IBDesignable commented on Tracker-ios/Supporting Files/Helpers/Date+Extensions.swift
> +        let date2 = Date.parse("01.01.2007")
@DmnUAll с авторами пришли к соглашению что функция инкременте/декремента тут как пятое колесо. 
Я думаю в скором времени ребята отрефачат дизайн и уроки (если было про это где-то). 

Приношу извинения, командный тупняк 😅 
Я думаю можно смело выпилить это 💩 и жить в прекрасном мире без этой фичи)))

2023-06-03 10:50 UTC, IBDesignable approved these changes
Оставляю пару комментариев относительно архитектуры, задача спринта принимаю)

2023-06-03 10:50 UTC, IBDesignable commented on Tracker-ios/Model/Constants.swift
> +//        static let none = ""
Можно убрать?)

2023-06-03 10:50 UTC, IBDesignable commented on Tracker-ios/Services/AnalyticsService.swift
> +        print("\nREPORT SENT FOR EVENT: \(event)\nWITH PARAMETERS: \(params)")
😅 спасибо)

2023-06-03 10:50 UTC, IBDesignable commented on Tracker-ios/Model/Constants.swift
> -        static let none = ""
Добавлю тут, что статические константы лучше перечислять в enum, так как структуру можно создать - а это как бы не то что мы здесь закладываем – здесь задача сделать некий NameSpace у констант

2023-06-03 10:50 UTC, IBDesignable commented on Tracker-ios/Services/AnalyticsService.swift
> +            return
Смотри, почти всегда у фрейворков для аналитики интерфейс, который позволяет посылать строки – никакими типами.

Я прошлый раз еще хотела добавить про это, но не доформулировала.
В идеале в своем приложении мы моделируем интерфейс другим образом: стараемся максимально ограничить тип данных, который можно послать в аналитику. 

`func report(event: TrackingEvent)` – такой интерфейс обычно используем на проде.
TrackingEvent - это протокол с двумя свойствами: trackingName: String и params: [String: Any].

Сущности которые его реализуют могут быть как структуры, так и енамы с ассоциированными типами. Если такую штуку построить, то код будет выглядеть как конфетка.

Этот коммент из серии почеленджить себя: на данном этапе эта реализация достаточна)

2023-06-03 10:50 UTC, IBDesignable commented on Tracker-ios/TrackersScreen/View/TrackersScreenController.swift
> +    }
Я тут в прошлый раз тоже недобила: тут с точки зрения арзитектуры MVVM определять какое действие показывается (пин/анпин) и сам комплишен на это действие – задача вьюмодели.

Тут хорошо бы иметь стейт: закреплена или нет, и интерфейс pinActionTitle, pinAction – а вот логику по определению того или другого, ты уже сможешь определить во viewModel. Так у тебя на один экшен в контроллере меньше собираться будет. 

`let pinAction = UIAction(title: viewModel.pinActionTitle, action: viewModel.pinAction)`

2023-06-03 10:50 UTC, IBDesignable commented on Tracker-ios/TrackersScreen/View/TrackersScreenController.swift
> +                                         "item": item])
и события по аналитике отправлять, тоже задача вьюмодели. Контроллер/вью в MVVM  достаточно тупенькие, просто передают действия пользователя в  сущность с логикой(viewModel)

2023-06-03 14:20 UTC, DmnUAll commented on Tracker-ios/Model/Constants.swift
> +//        static let none = ""
Убрал :)

2023-06-03 14:27 UTC, DmnUAll commented on Tracker-ios/Model/Constants.swift
> -        static let none = ""
@IBDesignable Привет! То есть - использовать String enum с ассоциативными значениями rawValue?

2023-06-03 14:29 UTC, DmnUAll commented on Tracker-ios/Services/AnalyticsService.swift
> +            return
Попробую применить :)

2023-06-03 14:59 UTC, merged